language: c++
sudo: required
dist: precise

compiler: gcc
env:
- LD_LIBRARY_PATH=/usr/local/lib

addons:
  ssh_known_hosts: msrd0.duckdns.org
  apt:
    sources:
      - sourceline: 'ppa:george-edison55/precise-backports'
      - sourceline: 'ppa:immerrr-k/qt5-backport'
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
      - sourceline: 'deb [arch=amd64] https://msrd0.duckdns.org/debian/ precise main'
        #key_url: 'http://http-keys.gnupg.net/pks/lookup?op=get&search=0xF8661CC669BF0588'
        key_url: 'https://msrd0.duckdns.org/debian/key.asc'
    packages:
      - cmake-data
      - cmake
      - g++-5
      - gcc-5
      - libqtwebapp-dev
      - qtchooser
      - qt5-default
      - realpath

before_install:
  - export CC=/usr/bin/gcc-5
  - export CXX=/usr/bin/g++-5
  - $CC --version
  - $CXX --version

install:
  - git clone --depth=1 https://github.com/msrd0/QSL.git
  - pushd QSL
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j2
  - sudo make install
  - popd

script:
  - mkdir build
  - pushd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j2 VERBOSE=1
  - sudo make install
  - popd
