language: c++
sudo: required
dist: precise

compiler: gcc
env:
- LD_LIBRARY_PATH=/usr/local/lib

addons:
  ssh_known_hosts: msrd0.duckdns.org
  apt:
    sources:
      - sourceline: 'ppa:george-edison55/precise-backports'
      - sourceline: 'ppa:immerrr-k/qt5-backport'
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
      - sourceline: 'deb [arch=amd64] https://msrd0.duckdns.org/debian/ precise main'
        #key_url: 'http://http-keys.gnupg.net/pks/lookup?op=get&search=0xF8661CC669BF0588'
        key_url: 'https://msrd0.duckdns.org/debian/key.asc'
    packages:
      - apt-utils
      - cmake-data
      - cmake
      - debhelper
      - dpkg-dev
      - fakeroot
      - g++-5
      - gcc-5
      - libqtwebapp-dev
      - qtchooser
      - qt5-default
      - realpath
      - spis
      - sshfs

before_install:
  - export CC=/usr/bin/gcc-5
  - export CXX=/usr/bin/g++-5
  - $CC --version
  - $CXX --version

before_script:
  - dig +short myip.opendns.com @resolver1.opendns.com
  - openssl aes-256-cbc -K $encrypted_e9321ec5018e_key -iv $encrypted_e9321ec5018e_iv -in .travis-keys.tar.xz.enc -out .travis-keys.tar.xz -d
  - tar xfa .travis-keys.tar.xz
  - mv alarmpi-debian* ~/.ssh/
  - touch ~/.ssh/config
  - echo "Host msrd0.duckdns.org" >>~/.ssh/config
  - echo "  IdentityFile ~/.ssh/alarmpi-debian" >>~/.ssh/config

script:
  - version=$(cat debian/changelog | grep -E '^intranet \(.+\) precise' | head -n1 | tr -d '(' | tr '-' ' ' | awk '{print $2}')
  - echo "KFG-Intranet $version"
  - wget "https://github.com/msrd0/KFG-Intranet/archive/v${version}.tar.gz"
  - tar xfz "v${version}.tar.gz"
  - pushd "KFG-Intranet-${version}"
  - echo 'install(FILES config.ini DESTINATION /etc/intranet)' | tee -a CMakeLists.txt
  - cp -R ../debian .
  - dpkg-buildpackage -us -uc
  - popd
  - ls intranet*

after_success:
  - make
  - test -d mount && sudo umount mount || true

after_script:
  - rm ~/.ssh/alarmpi-debian*
