language: c++
sudo: required
dist: trusty

compiler:
 - gcc
 - clang

addons:
  apt:
    packages:
      - qt5-default

install:
  - git clone --depth=1 https://github.com/msrd0/QtWebApp.git
  - pushd QtWebApp/QtWebApp
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j2
  - sudo make install
  - popd

  - git clone --depth=1 https://github.com/msrd0/QSL.git
  - pushd QSL
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j2
  - sudo make install
  - popd

script:
  - mkdir build
  - pushd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j2
  - sudo make install
  - popd
